#!/bin/bash

token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZW1haWwuY29tIiwiaWQiOiI2NTFkMjRjNTc1Yzk5N2E4YmI2MmYxMDcifSwiaWF0IjoxNjk2NDEyNDE2LCJleHAiOjE2OTY0MTMzMTZ9.jfkpVmrFdH5aT9mCwSqErDbyIEh5FxFFkOrvT4MlRPo'

id=651d330ff3ef6a07e37069e2

curl "http://127.0.0.1:3000/api/contacts/$id" \
  -X GET \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $token" \
