#!/bin/bash

payload_valid='{
  "email": "john@email.com",
  "password": "12345678"
}'

payload_invalid='{
  "email": "john@email.com",
  "password": "1234567"
}'


curl http://127.0.0.1:3000/api/users/login \
  -X POST \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d "$payload_valid"
