#!/bin/bash

payload='{
  "username": "John Doe",
  "email": "john@email.com",
  "password": "12345678"
}'

curl http://127.0.0.1:3000/api/users/register \
  -X POST \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d "$payload"
